"""STARK-ST 视觉目标跟踪器封装。

封装 STARK (Learning Spatio-Temporal Transformer for Visual Tracking) 跟踪器，
提供简洁的初始化/跟踪接口。

关键：自动处理 STARK 外部依赖的路径注入和 local.py 配置生成，
确保 `lib.test.evaluation.tracker` 等模块能够正常导入和使用。

依赖：
    - STARK 代码库 (git clone https://github.com/researchmm/Stark.git)
    - PyTorch + CUDA
    - 预训练权重文件 (.pth.tar)
"""

import os
import sys
from typing import Tuple, Optional


def _get_stark_root() -> str:
    """获取 STARK 代码库根目录。

    优先级：
    1. 环境变量 STARK_ROOT
    2. src.config 中的 STARK_ROOT
    3. 默认路径 D:\\github\\clone\\Stark
    """
    stark_root = os.environ.get("STARK_ROOT", "")
    if stark_root:
        return stark_root

    try:
        from src.config import STARK_ROOT as cfg_stark_root
        return cfg_stark_root
    except ImportError:
        pass

    return r"D:\github\clone\Stark"


def _inject_stark_path(stark_root: str):
    """将 STARK 代码库根目录注入 sys.path，使 lib.* 导入正常工作。"""
    if stark_root not in sys.path:
        sys.path.insert(0, stark_root)


def _ensure_stark_local_py(stark_root: str, save_dir: Optional[str] = None):
    """确保 STARK 的 local.py 环境配置文件存在。

    如果 local.py 缺失，会自动生成，指定 prj_dir 和 save_dir。
    STARK 的 env_settings() 函数通过 import lib.test.evaluation.local
    来加载环境配置。

    Args:
        stark_root: STARK 代码库根目录
        save_dir: checkpoint 保存目录，默认与 stark_root 相同
    """
    local_py_path = os.path.join(
        stark_root, "lib", "test", "evaluation", "local.py"
    )

    if os.path.exists(local_py_path):
        return  # 已存在，不覆盖

    if save_dir is None:
        save_dir = stark_root

    # 使用正斜杠避免转义问题
    prj_dir_normalized = stark_root.replace("\\", "/")
    save_dir_normalized = save_dir.replace("\\", "/")

    local_content = f'''"""Auto-generated by src/tracking/stark_wrapper.py — STARK local environment config."""

from lib.test.evaluation.environment import EnvSettings


def local_env_settings():
    settings = EnvSettings()

    # 项目根目录（含 experiments/ 目录）
    settings.prj_dir = '{prj_dir_normalized}'

    # 保存目录（含 checkpoints/ 目录）
    settings.save_dir = '{save_dir_normalized}'

    return settings
'''

    os.makedirs(os.path.dirname(local_py_path), exist_ok=True)
    with open(local_py_path, 'w', encoding='utf-8') as f:
        f.write(local_content)

    print(f"[OK] Auto-generated STARK local.py: {local_py_path}")


# =============================================================================
# 模块加载时自动执行 STARK 路径配置
# =============================================================================

_stark_root = _get_stark_root()
_inject_stark_path(_stark_root)
_ensure_stark_local_py(_stark_root)

# 现在可以安全导入 STARK 模块
from lib.test.evaluation.tracker import Tracker as _Tracker  # noqa: E402
from lib.test.parameter.stark_st import parameters as _parameters  # noqa: E402


class StarkTracker:
    """STARK-ST 视觉目标跟踪器。

    封装了 STARK-ST (Spatio-Temporal Transformer) 跟踪器的完整生命周期：
    初始化 → 逐帧跟踪。

    使用示例：
        >>> tracker = StarkTracker(checkpoint_rel_path="checkpoints/.../STARKST_ep0050.pth.tar")
        >>> tracker.initialize(first_frame, init_bbox=[x, y, w, h])
        >>> for frame in frames:
        ...     result = tracker.track(frame)
        ...     bbox = result['target_bbox']  # [x, y, w, h]
    """

    def __init__(
        self,
        checkpoint_rel_path: Optional[str] = None,
        params_name: str = "baseline",
        dataset_name: str = "OTB100",
        stark_root: Optional[str] = None,
        save_dir: Optional[str] = None
    ):
        """初始化 STARK 跟踪器。

        Args:
            checkpoint_rel_path: 预训练权重相对于 save_dir 的路径。
                                默认从 src.config 读取。
            params_name: 参数配置名称，对应 experiments/stark_st2/{params_name}.yaml
            dataset_name: 数据集名称，用于模板更新策略
            stark_root: STARK 代码库根目录（默认自动检测）
            save_dir: checkpoint 保存目录（默认与 stark_root 相同）
        """
        if stark_root is None:
            stark_root = _stark_root
        if save_dir is None:
            save_dir = stark_root

        # 确保 local.py 最新的（用户可能改了 save_dir）
        _ensure_stark_local_py(stark_root, save_dir)

        self.stark_root = stark_root
        self.save_dir = save_dir
        self.params_name = params_name
        self.dataset_name = dataset_name

        # 加载参数
        self.params = _parameters(params_name)

        # 允许覆盖 checkpoint 路径
        if checkpoint_rel_path is not None:
            self.params.checkpoint = os.path.join(
                save_dir, checkpoint_rel_path
            )

        self._tracker = None
        self._initialized = False

        print(f"[OK] STARK tracker params loaded")
        print(f"   Checkpoint: {self.params.checkpoint}")

    def initialize(self, first_frame, init_bbox: list) -> dict:
        """用第一帧和初始边界框初始化跟踪器。

        Args:
            first_frame: 第一帧图像 (BGR numpy array)
            init_bbox: 初始边界框 [x, y, w, h]

        Returns:
            初始化输出字典（可能包含 all_boxes）
        """
        # 每次初始化都要重新创建 tracker（STARK 的要求）
        self._tracker = _Tracker(
            name='stark_st',
            parameter_name=self.params_name,
            dataset_name=self.dataset_name
        ).create_tracker(self.params)

        init_info = {'init_bbox': init_bbox}
        result = self._tracker.initialize(first_frame, init_info)
        self._initialized = True

        if result is None:
            result = {}

        print("[OK] STARK tracker initialized")
        return result

    def track(self, frame) -> dict:
        """对当前帧进行跟踪，返回预测的边界框。

        Args:
            frame: 当前帧图像 (BGR numpy array)

        Returns:
            dict with keys:
                - 'target_bbox': [x, y, w, h] 预测边界框
                - 'conf_score': 置信度分数（可选）

        Raises:
            RuntimeError: 如果跟踪器尚未初始化
        """
        if not self._initialized:
            raise RuntimeError("跟踪器尚未初始化，请先调用 initialize()")

        result = self._tracker.track(frame)
        return result

    @property
    def is_initialized(self) -> bool:
        """跟踪器是否已初始化。"""
        return self._initialized
